### ISSUE TITLE
Empty string in AlbertaEnviroment response

### ISSUE THREAD

**Issue by wenta** [carldata/cwilong#31]
```
[ERROR] [06/28/2018 07:14:21.633] [Cwilong-akka.actor.default-dispatcher-11185] [akka.dispatch.Dispatcher] empty String
java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at scala.collection.immutable.StringLike.toFloat(StringLike.scala:312)
        at scala.collection.immutable.StringLike.toFloat$(StringLike.scala:312)
        at scala.collection.immutable.StringOps.toFloat(StringOps.scala:29)
        at carldata.cwilong.source.AlbertaEnviroment.$anonfun$parseSnowCSV$2(AlbertaEnviroment.scala:23)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at carldata.cwilong.source.AlbertaEnviroment.parseSnowCSV(AlbertaEnviroment.scala:23)
        at carldata.cwilong.source.AlbertaEnviroment.toDataPoint(AlbertaEnviroment.scala:13)
        at carldata.cwilong.Main$.$anonfun$createSourceConfig$2(Main.scala:72)
        at carldata.cwilong.source.HttpActor$$anonfun$receive$1.$anonfun$applyOrElse$2(HttpActor.scala:35)
        at carldata.cwilong.source.HttpActor$$anonfun$receive$1.$anonfun$applyOrElse$2$adapted(HttpActor.scala:34)
        at scala.util.Success.foreach(Try.scala:249)
        at scala.concurrent.Future.$anonfun$foreach$1$adapted(Future.scala:224)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by mjaniakcds** [comment]
When you have another data (temp and precip) then you set 0 for snow. When you have not another data, you haven't all and you don't insert to db.
